### ISSUE TITLE
Lesson 7. Ajax в Rails

### ISSUE THREAD

**Issue by popeskul** [popeskul/qna#36]
**Additional materials**
Manage latency for ajax responses in tests: 
[http://connect.thinknetica.com/t/sovety-uvelichenie-vremeni-ozhidaniya-ajax-otveta/976
](http://connect.thinknetica.com/t/sovety-uvelichenie-vremeni-ozhidaniya-ajax-otveta/976)

Gem jquery-rails: [https://github.com/rails/jquery-rails](https://github.com/rails/jquery-rails)

JQuery documentation: [https://api.jquery.com/](https://api.jquery.com/)

**Step:**

- [x] [User can answer the question with the help of AJAX.](https://github.com/peterjj91/qna/issues/38)
- [x] [Create Ajax.](https://github.com/peterjj91/qna/issues/37)
- [ ] [Only the author can edit his question.](https://github.com/peterjj91/qna/issues/39)
- [x] [Only the author can edit his answer.](https://github.com/peterjj91/qna/issues/40)
- [x] [Redoing the removal of responses to ajax.](https://github.com/peterjj91/qna/issues/41)
- [ ] [The author of a question can choose the best answer for his question.](https://github.com/peterjj91/qna/issues/42)
- [ ] [The author of a question may choose another answer as the best if the question has already chosen the best answer](https://github.com/peterjj91/qna/issues/43)
- [ ] [If the question has the best answer, it is displayed first in the list of answers.](https://github.com/peterjj91/qna/issues/44)
